# Generated by Django 5.2.12 on 2026-03-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mutualist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prenoms')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nom')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Numero')),
            ],
            options={
                'verbose_name': 'Mutualiste',
                'verbose_name_plural': 'Mutualistes',
            },
        ),
    ]
