# Generated by Django 5.2.12 on 2026-03-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre du message')),
                ('content', models.TextField(verbose_name='Contenu du message')),
                ('mutualists', models.ManyToManyField(related_name='messages', to='smsapp.mutualist')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
